# Generated by Django 5.1.3 on 2025-06-13 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisComunas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='cantidad_habitantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comuna',
            name='fecha_fundacion',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='comuna',
            name='vulnerabilidad',
            field=models.FloatField(default=0.0),
        ),
    ]
