# Generated by Django 5.1.3 on 2025-06-13 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisComunas', '0002_comuna_cantidad_habitantes_comuna_fecha_fundacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='vulnerabilidad',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
